// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2024, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional,
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type CreateChatCompletionRequest record {
    *CreateModelResponseProperties;
    ChatCompletionRequestMessage[] messages;
    ModelIdsShared model;
    ResponseModalities modalities?;
    Verbosity verbosity?;
    ReasoningEffort reasoning_effort?;
    int max_completion_tokens?;
    decimal frequency_penalty = 0;
    decimal presence_penalty = 0;
    record {record {"approximate" 'type; WebSearchLocation approximate;} user_location?; WebSearchContextSize search_context_size?;} web_search_options?;
    int top_logprobs?;
    ResponseFormatText|ResponseFormatJsonSchema|ResponseFormatJsonObject response_format?;
    record {VoiceIdsOrCustomVoice voice; "wav"|"aac"|"mp3"|"flac"|"opus"|"pcm16" format;} audio?;
    boolean store = false;
    boolean 'stream = false;
    StopConfiguration stop?;
    record {|int...;|} logit_bias?;
    boolean logprobs = false;
    int max_tokens?;
    int n = 1;
    PredictionContent prediction?;
    int seed?;
    ChatCompletionStreamOptions stream_options?;
    (ChatCompletionTool|CustomToolChatCompletions)[] tools?;
    ChatCompletionToolChoiceOption tool_choice?;
    ParallelToolCalls parallel_tool_calls?;
    "none"|"auto"|ChatCompletionFunctionCallOption function_call?;
    ChatCompletionFunctions[] functions?;
};

public type CreateChatCompletionResponse record {
    # A unique identifier for the chat completion.
    string id;
    # A list of chat completion choices. Can be more than one if `n` is greater than 1.
    record {"stop"|"length"|"tool_calls"|"content_filter"|"function_call" finish_reason; int index; ChatCompletionResponseMessage message; anydata logprobs;}[] choices;
    # The Unix timestamp (in seconds) of when the chat completion was created.
    int created;
    # The model used for the chat completion.
    string model;
    ServiceTier service_tier?;
    # This fingerprint represents the backend configuration that the model runs with.
    #
    # Can be used in conjunction with the `seed` request parameter to understand when backend changes have been made that might impact determinism.
    #
    # # Deprecated
    @deprecated
    string system_fingerprint?;
    # The object type, which is always `chat.completion`.
    "chat.completion" 'object;
    # Usage statistics for the completion request.
    CompletionUsage usage?;
};

public type ChatCompletionRequestMessage ChatCompletionRequestDeveloperMessage|ChatCompletionRequestSystemMessage|ChatCompletionRequestUserMessage|ChatCompletionRequestAssistantMessage|ChatCompletionRequestToolMessage|ChatCompletionRequestFunctionMessage;

# Developer-provided instructions that the model should follow, regardless of
# messages sent by the user. With o1 models and newer, `developer` messages
# replace the previous `system` messages.
public type ChatCompletionRequestDeveloperMessage record {
    # The contents of the developer message.
    string|ChatCompletionRequestMessageContentPartText[] content;
    # The role of the messages author, in this case `developer`.
    "developer" role;
    # An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    string name?;
};

public type ChatCompletionRequestSystemMessage record {
    # The contents of the system message.
    string|ChatCompletionRequestSystemMessageContentPart[] content;
    # The role of the messages author, in this case `system`.
    "system" role;
    # An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    string name?;
};

public type ChatCompletionRequestUserMessage record {
    # The contents of the user message.
    string|ChatCompletionRequestUserMessageContentPart[] content;
    # The role of the messages author, in this case `user`.
    "user" role;
    # An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    string name?;
};

public type ChatCompletionRequestAssistantMessage record {
    anydata content?;
    anydata refusal?;
    # The role of the messages author, in this case `assistant`.
    "assistant" role;
    # An optional name for the participant. Provides the model information to differentiate between participants of the same role.
    string name?;
    anydata audio?;
    # The tool calls generated by the model, such as function calls.
    ChatCompletionMessageToolCalls tool_calls?;
    anydata function_call?;
};

public type ChatCompletionRequestToolMessage record {
    # The role of the messages author, in this case `tool`.
    "tool" role;
    # The contents of the tool message.
    string|ChatCompletionRequestToolMessageContentPart[] content;
    # Tool call that this message is responding to.
    string tool_call_id;
};

@deprecated
public type ChatCompletionRequestFunctionMessage record {
    # The role of the messages author, in this case `function`.
    "function" role;
    # The contents of the function message.
    anydata content;
    # The name of the function to call.
    string name;
};

public type ChatCompletionResponseMessage record {
    anydata content;
    anydata refusal;
    # The tool calls generated by the model, such as function calls.
    ChatCompletionMessageToolCalls tool_calls?;
    # Annotations for the message, when applicable, as when using the
    # [web search tool](/docs/guides/tools-web-search?api-mode=chat).
    record {"url_citation" 'type; record {int end_index; int start_index; string url; string title;} url_citation;}[] annotations?;
    # The role of the author of this message.
    "assistant" role;
    # Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
    ChatCompletionResponseMessage_function_call function_call?;
    anydata audio?;
};

# Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called, as generated by the model.
#
# # Deprecated
@deprecated
public type ChatCompletionResponseMessage_function_call record {
    # The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    string arguments;
    # The name of the function to call.
    string name;
};

# A text content part of a prompt.
public type ChatCompletionRequestMessageContentPartText record {
    # The type of the content part.
    "text" 'type;
    # The text content.
    string text;
};

public type ChatCompletionRequestMessageContentPartImage record {
    # The type of the content part.
    "image_url" 'type;
    ChatCompletionRequestMessageContentPartImage_image_url image_url;
};

public type ChatCompletionRequestMessageContentPartImage_image_url record {
    # Either a URL of the image or the base64 encoded image data.
    string url;
    # Specifies the detail level of the image. Learn more in the [Vision guide](/docs/guides/vision#low-or-high-fidelity-image-understanding).
    "auto"|"low"|"high" detail = "auto";
};

# Learn about [audio inputs](/docs/guides/audio).
public type ChatCompletionRequestMessageContentPartAudio record {
    # The type of the content part. Always `input_audio`.
    "input_audio" 'type;
    ChatCompletionRequestMessageContentPartAudio_input_audio input_audio;
};

public type ChatCompletionRequestMessageContentPartAudio_input_audio record {
    # Base64 encoded audio data.
    string data;
    # The format of the encoded audio data. Currently supports "wav" and "mp3".
    "wav"|"mp3" format;
};

# Learn about [file inputs](/docs/guides/text) for text generation.
public type ChatCompletionRequestMessageContentPartFile record {
    # The type of the content part. Always `file`.
    "file" 'type;
    ChatCompletionRequestMessageContentPartFile_file file;
};

public type ChatCompletionRequestMessageContentPartFile_file record {
    # The base64 encoded file data, used when passing the file to the API directly.
    string file_data?;
    # The ID of an uploaded file to use as input.
    string file_id?;
    # The name of the file, used when passing the file to the API directly.
    string filename?;
};

public type ChatCompletionRequestSystemMessageContentPart ChatCompletionRequestMessageContentPartText;

public type ChatCompletionRequestUserMessageContentPart ChatCompletionRequestMessageContentPartText|ChatCompletionRequestMessageContentPartImage|ChatCompletionRequestMessageContentPartAudio|ChatCompletionRequestMessageContentPartFile;

public type ChatCompletionRequestToolMessageContentPart ChatCompletionRequestMessageContentPartText;

public type ChatCompletionRequestAssistantMessageContentPart ChatCompletionRequestMessageContentPartText|ChatCompletionRequestMessageContentPartRefusal;

public type ChatCompletionRequestMessageContentPartRefusal record {
    # The type of the content part.
    "refusal" 'type;
    # The refusal message generated by the model.
    string refusal;
};

public type ChatCompletionTool record {
    # The type of the tool. Currently, only `function` is supported.
    "function" 'type;
    FunctionObject 'function;
};

# A custom tool that processes input using a specified format.
public type CustomToolChatCompletions record {
    # The type of the custom tool. Always `custom`.
    "custom" 'type;
    # Properties of the custom tool.
    Custom\ tool\ properties custom;
};

public type Custom\ tool\ properties record {
    string name;
    string description?;
    record {"text" 'type;}|record {"grammar" 'type; record {string definition; "lark"|"regex" syntax;} grammar;} format?;
};

public type ChatCompletionToolChoiceOption "none"|"auto"|"required"|ChatCompletionAllowedToolsChoice|ChatCompletionNamedToolChoice|ChatCompletionNamedToolChoiceCustom;

public type ChatCompletionAllowedToolsChoice record {
    # Allowed tool configuration type. Always `allowed_tools`.
    "allowed_tools" 'type;
    # Constrains the tools available to the model to a pre-defined set.
    ChatCompletionAllowedTools allowed_tools;
};

public type ChatCompletionAllowedTools record {
    # Constrains the tools available to the model to a pre-defined set.
    #
    # `auto` allows the model to pick from among the allowed tools and generate a
    # message.
    #
    # `required` requires the model to call one or more of the allowed tools.
    "auto"|"required" mode;
    # A list of tool definitions that the model should be allowed to call.
    #
    # For the Chat Completions API, the list of tool definitions might look like:
    # ```json
    # [
    #   { "type": "function", "function": { "name": "get_weather" } },
    #   { "type": "function", "function": { "name": "get_time" } }
    # ]
    # ```
    record {}[] tools;
};

public type ChatCompletionNamedToolChoice record {
    # For function calling, the type is always `function`.
    "function" 'type;
    AssistantsNamedToolChoice_function 'function;
};

public type AssistantsNamedToolChoice_function record {
    # The name of the function to call.
    string name;
};

public type ChatCompletionNamedToolChoiceCustom record {
    # For custom tool calling, the type is always `custom`.
    "custom" 'type;
    ChatCompletionNamedToolChoiceCustom_custom custom;
};

public type ChatCompletionNamedToolChoiceCustom_custom record {
    # The name of the custom tool.
    string name;
};

public type ChatCompletionFunctions record {
    # A description of what the function does, used by the model to choose when and how to call the function.
    string description?;
    # The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
    string name;
    # The parameters the functions accepts, described as a JSON Schema object. See the [guide](/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format.
    #
    # Omitting `parameters` defines a function with an empty parameter list.
    FunctionParameters parameters?;
};

public type ChatCompletionFunctionCallOption record {
    # The name of the function to call.
    string name;
};

public type FunctionObject record {
    # A description of what the function does, used by the model to choose when and how to call the function.
    string description?;
    # The name of the function to be called. Must be a-z, A-Z, 0-9, or contain underscores and dashes, with a maximum length of 64.
    string name;
    # The parameters the functions accepts, described as a JSON Schema object. See the [guide](/docs/guides/function-calling) for examples, and the [JSON Schema reference](https://json-schema.org/understanding-json-schema/) for documentation about the format.
    #
    # Omitting `parameters` defines a function with an empty parameter list.
    FunctionParameters parameters?;
    anydata strict?;
};

public type FunctionParameters record {
};

public type ChatCompletionMessageToolCalls (ChatCompletionMessageToolCall|ChatCompletionMessageCustomToolCall)[];

public type ChatCompletionMessageToolCall record {
    # The ID of the tool call.
    string id;
    # The type of the tool. Currently, only `function` is supported.
    "function" 'type;
    # The function that the model called.
    ChatCompletionMessageToolCall_function 'function;
};

public type ChatCompletionMessageToolCall_function record {
    # The name of the function to call.
    string name;
    # The arguments to call the function with, as generated by the model in JSON format. Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema. Validate the arguments in your code before calling your function.
    string arguments;
};

public type ChatCompletionMessageCustomToolCall record {
    # The ID of the tool call.
    string id;
    # The type of the tool. Always `custom`.
    "custom" 'type;
    # The custom tool that the model called.
    ChatCompletionMessageCustomToolCall_custom custom;
};

public type ChatCompletionMessageCustomToolCall_custom record {
    # The name of the custom tool.
    string name;
    # The output of the custom tool call.
    string output;
};

# An object specifying the format that the model must output.
public type ResponseFormatText record {
    # The type of response format being defined. Always `text`.
    "text" 'type;
};

# JSON object response format. An older method of generating JSON responses.
# Using `json_schema` is recommended for models that support it. Note that the
# model will not generate JSON without a system or user message instructing it
# to do so.
public type ResponseFormatJsonObject record {
    # The type of response format being defined. Always `json_object`.
    "json_object" 'type;
};

# JSON Schema response format. Used to generate structured JSON responses.
# Learn more about [Structured Outputs](/docs/guides/structured-outputs).
public type ResponseFormatJsonSchema record {
    # The type of response format being defined. Always `json_schema`.
    "json_schema" 'type;
    # Structured Outputs configuration options, including a JSON Schema.
    JSON\ schema json_schema;
};

public type JSON\ schema record {
    string description?;
    string name;
    ResponseFormatJsonSchemaSchema schema?;
    anydata strict?;
};

# The schema for the response format, described as a JSON Schema object.
# Learn how to build JSON schemas [here](https://json-schema.org/).
public type ResponseFormatJsonSchemaSchema record {
};

public type CreateModelResponseProperties record {
    *ModelResponseProperties;
    int top_logprobs?;
};

public type ModelResponseProperties record {
    # A list of metadata keys to filter the Chat Completions by. Example:
    #
    # `metadata[key1]=value1&metadata[key2]=value2`
    Metadata metadata?;
    anydata top_logprobs?;
    anydata temperature?;
    anydata top_p?;
    # This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key` instead to maintain caching optimizations.
    # A stable identifier for your end-users.
    # Used to boost cache hit rates by better bucketing similar requests and  to help OpenAI detect and prevent abuse. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
    #
    # # Deprecated
    @deprecated
    string user?;
    # A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies.
    # The IDs should be a string that uniquely identifies each user. We recommend hashing their username or email address, in order to avoid sending us any identifying information. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
    string safety_identifier?;
    # Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field. [Learn more](/docs/guides/prompt-caching).
    string prompt_cache_key?;
    ServiceTier service_tier?;
    anydata prompt_cache_retention?;
};

public type ModelIdsShared string|"gpt-5.2"|"gpt-5.2-2025-12-11"|"gpt-5.2-chat-latest"|"gpt-5.2-pro"|"gpt-5.2-pro-2025-12-11"|"gpt-5.1"|"gpt-5.1-2025-11-13"|"gpt-5.1-codex"|"gpt-5.1-mini"|"gpt-5.1-chat-latest"|"gpt-5"|"gpt-5-mini"|"gpt-5-nano"|"gpt-5-2025-08-07"|"gpt-5-mini-2025-08-07"|"gpt-5-nano-2025-08-07"|"gpt-5-chat-latest"|"gpt-4.1"|"gpt-4.1-mini"|"gpt-4.1-nano"|"gpt-4.1-2025-04-14"|"gpt-4.1-mini-2025-04-14"|"gpt-4.1-nano-2025-04-14"|"o4-mini"|"o4-mini-2025-04-16"|"o3"|"o3-2025-04-16"|"o3-mini"|"o3-mini-2025-01-31"|"o1"|"o1-2024-12-17"|"o1-preview"|"o1-preview-2024-09-12"|"o1-mini"|"o1-mini-2024-09-12"|"gpt-4o"|"gpt-4o-2024-11-20"|"gpt-4o-2024-08-06"|"gpt-4o-2024-05-13"|"gpt-4o-audio-preview"|"gpt-4o-audio-preview-2024-10-01"|"gpt-4o-audio-preview-2024-12-17"|"gpt-4o-audio-preview-2025-06-03"|"gpt-4o-mini-audio-preview"|"gpt-4o-mini-audio-preview-2024-12-17"|"gpt-4o-search-preview"|"gpt-4o-mini-search-preview"|"gpt-4o-search-preview-2025-03-11"|"gpt-4o-mini-search-preview-2025-03-11"|"chatgpt-4o-latest"|"codex-mini-latest"|"gpt-4o-mini"|"gpt-4o-mini-2024-07-18"|"gpt-4-turbo"|"gpt-4-turbo-2024-04-09"|"gpt-4-0125-preview"|"gpt-4-turbo-preview"|"gpt-4-1106-preview"|"gpt-4-vision-preview"|"gpt-4"|"gpt-4-0314"|"gpt-4-0613"|"gpt-4-32k"|"gpt-4-32k-0314"|"gpt-4-32k-0613"|"gpt-3.5-turbo"|"gpt-3.5-turbo-16k"|"gpt-3.5-turbo-0301"|"gpt-3.5-turbo-0613"|"gpt-3.5-turbo-1106"|"gpt-3.5-turbo-0125"|"gpt-3.5-turbo-16k-0613";

public type ServiceTier anydata;

# Usage statistics for the completion request.
public type CompletionUsage record {
    # Number of tokens in the generated completion.
    int completion_tokens = 0;
    # Number of tokens in the prompt.
    int prompt_tokens = 0;
    # Total number of tokens used in the request (prompt + completion).
    int total_tokens = 0;
    # Breakdown of tokens used in a completion.
    CompletionUsage_completion_tokens_details completion_tokens_details?;
    # Breakdown of tokens used in the prompt.
    CompletionUsage_prompt_tokens_details prompt_tokens_details?;
};

# Breakdown of tokens used in a completion.
public type CompletionUsage_completion_tokens_details record {
    # When using Predicted Outputs, the number of tokens in the
    # prediction that appeared in the completion.
    int accepted_prediction_tokens = 0;
    # Audio input tokens generated by the model.
    int audio_tokens = 0;
    # Tokens generated by the model for reasoning.
    int reasoning_tokens = 0;
    # When using Predicted Outputs, the number of tokens in the
    # prediction that did not appear in the completion. However, like
    # reasoning tokens, these tokens are still counted in the total
    # completion tokens for purposes of billing, output, and context window
    # limits.
    int rejected_prediction_tokens = 0;
};

# Breakdown of tokens used in the prompt.
public type CompletionUsage_prompt_tokens_details record {
    # Audio input tokens present in the prompt.
    int audio_tokens = 0;
    # Cached tokens present in the prompt.
    int cached_tokens = 0;
};

public type ResponseModalities anydata;

public type Verbosity anydata;

public type ReasoningEffort anydata;

# Not supported with latest reasoning models `o3` and `o4-mini`.
#
# Up to 4 sequences where the API will stop generating further tokens. The
# returned text will not contain the stop sequence.
public type StopConfiguration string|string[];

# Static predicted output content, such as the content of a text file that is
# being regenerated.
public type PredictionContent record {
    # The type of the predicted content you want to provide. This type is
    # currently always `content`.
    "content" 'type;
    # The content that should be matched when generating a model response.
    # If generated tokens would match this content, the entire model response
    # can be returned much more quickly.
    string|ChatCompletionRequestMessageContentPartText[] content;
};

public type ChatCompletionStreamOptions anydata;

# Whether to enable [parallel function calling](/docs/guides/function-calling#configuring-parallel-function-calling) during tool use.
public type ParallelToolCalls boolean;

# Approximate location parameters for the search.
public type WebSearchLocation record {
    # The two-letter
    # [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of the user,
    # e.g. `US`.
    string country?;
    # Free text input for the region of the user, e.g. `California`.
    string region?;
    # Free text input for the city of the user, e.g. `San Francisco`.
    string city?;
    # The [IANA timezone](https://timeapi.io/documentation/iana-timezones)
    # of the user, e.g. `America/Los_Angeles`.
    string timezone?;
};

# High level guidance for the amount of context window space to use for the
# search. One of `low`, `medium`, or `high`. `medium` is the default.
public type WebSearchContextSize "low"|"medium"|"high";

# A built-in voice name or a custom voice reference.
public type VoiceIdsOrCustomVoice VoiceIdsShared|record {string id;};

public type VoiceIdsShared string|"alloy"|"ash"|"ballad"|"coral"|"echo"|"sage"|"shimmer"|"verse"|"marin"|"cedar";

public type Metadata anydata;

public type ChatCompletionTokenLogprob record {
    # The token.
    string token;
    # The log probability of this token, if it is within the top 20 most likely tokens. Otherwise, the value `-9999.0` is used to signify that the token is very unlikely.
    decimal logprob;
    anydata bytes;
    # List of the most likely tokens and their log probability, at this token position. In rare cases, there may be fewer than the number of requested `top_logprobs` returned.
    record {string token; decimal logprob; anydata bytes;}[] top_logprobs;
};
